[package]
name = "c2pa_lib"
version = "0.1.0"
edition = "2024"

[lib]
name = "c2pa_lib"
crate-type = ["cdylib"]

[dependencies]
jni = "0.21"
once_cell = "1.19"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
log = "0.4"
android_logger = "0.13"
